### ISSUE TITLE
1.2.1 Product Overview

### ISSUE THREAD

**Issue by minXnub** [minXnub/ICT2101-P4-3-Project#17]

**Comment by zoee-Y** [comment]
Wrote the paragraph for this section, decided on the tools and languages to be used for our project.

**Comment by zoee-Y** [comment]
Came up with the three-tiered architecture diagram, with Presentation, Application and Logical layer, after some research on the architecture diagrams.

**Comment by zoee-Y** [comment]
Changed the three-tiered architecture diagram to only system and database after asking the professor some questions during lab session.

**Comment by zoee-Y** [comment]
Completed.
