### ISSUE TITLE
1.4.2 Project Management

### ISSUE THREAD

**Issue by minXnub** [minXnub/ICT2101-P4-3-Project#20]
Gantt Chart
https://docs.google.com/spreadsheets/d/1P6o2QLqJXjf93TGs4Vj24MOylW6LWjjHitjJYCuA2Kk/edit?usp=sharing
WBS (Page 2)
https://drive.google.com/file/d/1SlhpwwnInkw52a7ck0cZ0qUoId-uL4ro/view?usp=sharing

**Comment by dennisawj** [comment]
Reviewed

**Comment by zoee-Y** [comment]
Reviewed

**Comment by geethika-m** [comment]
Reviewed

**Comment by minXnub** [comment]
Closed as completed
