### ISSUE TITLE
Update Figma Prototype with changes after client meeting

### ISSUE THREAD

**Issue by minXnub** [minXnub/ICT2101-P4-3-Project#23]
To be reviewed by: Zoe and Shu Min

To be completed before week 8.

**Comment by geethika-m** [comment]
Changes to be done:

1. Create page for Manager to update pilot's training
2.

**Comment by minXnub** [comment]
Reviewed

**Comment by zoee-Y** [comment]
Reviewed

**Comment by geethika-m** [comment]
Closed as completed
