### ISSUE TITLE
1.2.3 Assumptions and Dependencies

### ISSUE THREAD

**Issue by minXnub** [minXnub/ICT2101-P4-3-Project#34]

**Comment by zoee-Y** [comment]
Wrote the assumptions that we made of our product and the client, according to the requirements given for this project, in order to proceed with the rest of the project.

**Comment by geethika-m** [comment]
Wrote the 1st assumption in the report which is that we assume that there are at least 30 pilots in the company but are unsure of the exact number, since the client has only mentioned that the company is small.

**Comment by zoee-Y** [comment]
Closed as completion
