### ISSUE TITLE
1.1.2 Related Background Literature

### ISSUE THREAD

**Issue by minXnub** [minXnub/ICT2101-P4-3-Project#35]

**Comment by dennisawj** [comment]
Researched on:
- How airline crew works
- Process behind flight schedules
- Crew Management in Airlines
- Crew Management Tools
- Similar Work Management Systems did by other airlines (Boeing)
    -   The use case of their system 
- How Airline crew are ranked
- Features that other airline software companies have (Takeflite)

**Comment by dennisawj** [comment]
Completed writing of Background Literature. Please assist on Reviewing

**Comment by zoee-Y** [comment]
Reviewed

**Comment by dennisawj** [comment]
Completed
