### ISSUE TITLE
1.3.1 User Interface Requirements

### ISSUE THREAD

**Issue by minXnub** [minXnub/ICT2101-P4-3-Project#38]

**Comment by minXnub** [comment]
Reviewed

**Comment by dennisawj** [comment]
Reviewed

**Comment by geethika-m** [comment]
Wrote the User Interface requirements for our project, based on the initial requirements and feedback during the client meeting about our prototype.

**Comment by geethika-m** [comment]
Completed

**Comment by geethika-m** [comment]
Close as completed
