### ISSUE TITLE
1.3.5 Other Requirements

### ISSUE THREAD

**Issue by minXnub** [minXnub/ICT2101-P4-3-Project#39]

**Comment by minXnub** [comment]
Reviewed

**Comment by dennisawj** [comment]
Reviewed

**Comment by zoee-Y** [comment]
Reviewed

**Comment by geethika-m** [comment]
Wrote the other requirements, which refers to requirements that dont fit in any of the other categories, for our project, based on our discussions, the project brief, and the client meeting.

**Comment by geethika-m** [comment]
Completed

**Comment by geethika-m** [comment]
Closed as completed
