### ISSUE TITLE
1.1.4 References and Acknowledgments

### ISSUE THREAD

**Issue by minXnub** [minXnub/ICT2101-P4-3-Project#42]

**Comment by zoee-Y** [comment]
Added reference [2]: 8 Big Advantages of using MySQL.

**Comment by dennisawj** [comment]
Added Reference [1]: How Airline Crews Work
Added Reference [3]: In-Service Data Program Helps Boeing Design, Build and support Airplanes
Added Reference [4]: Airline Crew Rostering: Problem Types, Modeling, and Optimization
Added Reference [5]: The Complex Process behind your airline's Flight Schedule!
Added Reference [6]: Crew Management in Airlines
Added Reference [7]: 14 Airline Crew Scheduling
Added Reference [8]: Airline Crew Scheduling: models
Added Reference [9]:  Crew Management Tool Improve Operating Efficiency. Boeing.
Added Reference [10]: Pilot & Crew Management.

**Comment by dennisawj** [comment]
Completed adding all references, Closing this.
