### ISSUE TITLE
1.3.4.2 Safety and Security Requirements

### ISSUE THREAD

**Issue by zoee-Y** [minXnub/ICT2101-P4-3-Project#57]

**Comment by minXnub** [comment]
Reviewed

**Comment by dennisawj** [comment]
Reviewed

**Comment by zoee-Y** [comment]
Reviewed

**Comment by geethika-m** [comment]
Wrote the safety requirements for our project, based on our discussions, the project brief, and the client meeting.

**Comment by geethika-m** [comment]
Completed

**Comment by zoee-Y** [comment]
Wrote security requirements for 2 factor authentication using location

**Comment by geethika-m** [comment]
Closed as completed
