### ISSUE TITLE
2.1.1 Product Scope

### ISSUE THREAD

**Issue by minXnub** [minXnub/ICT2101-P4-3-Project#65]
To be completed by 10/14/22

**Comment by dennisawj** [comment]
Things to Improve on : 
Write about chosen SDLC and how we are going to show that we used it

**Comment by dennisawj** [comment]
- Discussed with the Team which SDLC we using and decided on the waterfall methodology.
- Added in our SDLC and rationale on why we choose it and how we implemented it.

Team please help to review thanks

**Comment by geethika-m** [comment]
Reviewed

**Comment by minXnub** [comment]
Reviewed

**Comment by zoee-Y** [comment]
Reviewed

**Comment by dennisawj** [comment]
Product Scope completed
