### ISSUE TITLE
2.1.2 Intended Audience and Document Overview

### ISSUE THREAD

**Issue by minXnub** [minXnub/ICT2101-P4-3-Project#66]
To be completed by 14/10/22

**Comment by dennisawj** [comment]
Things to Change:
- Amend according to the new sequence of reading for the new M2 Report
- Update new reasoning to the new sequence

**Comment by dennisawj** [comment]
Added some reasoning to the recommended reading sequence .
Will keep this open in case there is any amendment needed to the reading sequence.

**Comment by dennisawj** [comment]
Completed on 14/10/22
