### ISSUE TITLE
2.3.1 Architectural Design

### ISSUE THREAD

**Issue by minXnub** [minXnub/ICT2101-P4-3-Project#69]

**Comment by zoee-Y** [comment]
To do:

- Describe team's software architectural design
- Come up with component diagram

**Comment by zoee-Y** [comment]
Tuesday, 18 October 2022
Discussion with team:
- Software architecture
- Completed System context diagram and Container diagram
- To ask prof to look through in labtorial on Friday, 21 Oct 2022

**Comment by zoee-Y** [comment]
Thursday, 20 October 2022

Wrote the content for 3.1 Architectural design
- Architectural design, web application
- MVC pattern
- added some comments/questions in the document, about the use cases and webpages

Other members to help review and make changes if necessary

**Comment by dennisawj** [comment]
Reviewed. Added my comments to answer some of your questions in the documents.

**Comment by zoee-Y** [comment]
23/10/22, 9.53pm:
Replied to Dennis' comments to clarify on some questions and build on the response given

**Comment by zoee-Y** [comment]
Friday, 22/10/22
After going through the labtorial, we have things to further discuss
To do:
- Follow up discussion with team by 27/10/22 to finalize architectural and software design
- Follow up discussion with team by 27/10/22 to redesign system architecture diagram, so we can include it in the report as well.

Other changes:
- I have removed system context diagram and container diagram as these are not needed

**Comment by dennisawj** [comment]
added Justification on our Software design. Please help to review

**Comment by zoee-Y** [comment]
Reviewed justification

**Comment by zoee-Y** [comment]
Team meeting on 25/10/22:
Things done as a team:
- Finalized decision on architectural and software design pattern

**Comment by zoee-Y** [comment]
Team meeting on 27/10/22:
Things done as a team:
- Created a new system architecture diagram
- Created our component diagram
Other things done:
- Added System context diagram and Container diagram back into the report

**Comment by zoee-Y** [comment]
Friday, 28/10/22 labtorial session:
After asking the professor to look through our content, we have to change:
- Component diagram: Disassembling and then grouping our components in accordance to MVC pattern

**Comment by minXnub** [comment]
completed draft of sequence diagram for UC-10 on 28 Oct 2022 and gathered feedback on 28 Oct tutorial session.

**Comment by minXnub** [comment]
Updated Use Case Descriptions:

- UC-1: 

> Description and Alternative Scenarios changed to include a condition where pilot has not accepted any jobs for the week. System will notify Pilot that no jobs has been accepted yet. Postcondition updated to clearly state the outcome.

**Comment by dennisawj** [comment]
completed sequence diagram for UC-9 on 29 Oct 2022

**Comment by minXnub** [comment]
Updated UC-10 based on feedback gathered and completed the explanation for the sequence diagram.

**Comment by geethika-m** [comment]
Completed sequence diagram for UC-6, and completed explanation for it in the report on 29 Oct 2022.

**Comment by zoee-Y** [comment]
Completed on 29/10/22
