### ISSUE TITLE
2.3.2 Detailed Design

### ISSUE THREAD

**Issue by minXnub** [minXnub/ICT2101-P4-3-Project#70]

**Comment by zoee-Y** [comment]
To do:

- Discussion with team on software classes to be used in project
- Come up with class diagram
- Come up with sequence diagram
- In report, describe team's software classes and use part of the class diagram for explanation
- Sequence diagram can be used to explain design flow between objects

**Comment by zoee-Y** [comment]
Discussed class diagram and completed class diagram on Tuesday, 18 October 2022, to ask prof to look through in labtorial on Friday, 21 Oct 2022

**Comment by zoee-Y** [comment]
Thursday, 20 October 2022
- Came up with a sequence diagram for UC3: Add job availability, with main flow and alternate scenario
- To ask prof if it is okay and make changes accordingly

**Comment by zoee-Y** [comment]
Friday, 21/10/22
After labtorial on Friday, we have gotten feedback on the sequence diagram I made for UC3
- Revise the sequence diagram for UC3 with team, work with everyone to make sequence diagrams for the important use cases, by 28/10/22 (at least 5 according to Prof Marcus)
- Make any necessary changes to the class diagram by 28/10/22

**Comment by zoee-Y** [comment]
Sunday, 23/10/22, 11.25pm
- Zhi Wei (me): Wrote description and explanation for section 3.2 of the report, taking closeups of the class diagram that we have so far

Other members to look through the description and explanations, and reply to the comments I have written under 3.2.


To do:
- The team might possibly make changes to class diagram when creating the sequence diagrams, which I would then have to update the images accordingly
- To include the completed sequence diagrams after it is done, and add to the explanation, where applicable

**Comment by zoee-Y** [comment]
Team meeting on 25/10/22:
Things done as a team:
- Decided on the 5 use cases that we will do sequence diagrams for

The allocation of use cases is as follows:
- Zhi wei: UC1, UC3
- Dennis: UC9
- Shu min: UC10
- Geethika: UC6

**Comment by zoee-Y** [comment]
Friday, 28/10/22 labtorial session:
After asking the professor to look through our content, we have to change:
- Use case description for UC1 - Accept weekly job assignments
- Use case descriptions for all use cases: Precondition and post condition to include database operations
- Sequence diagrams: Removal of database from the sequence diagrams, due to specifying database operations in use case descriptions
- Class diagram: grouping in accordance to MVC pattern

**Comment by zoee-Y** [comment]
Saturday, 29/10/22:
- Updated use case descriptions to include database connections, as discussed during labtorial (all use cases except UC9)

**Comment by minXnub** [comment]
Updated Use Case Descriptions to ensure that content is aligned.

- UC-1: 

> Description and Alternative Scenarios changed to include a condition where pilot has not accepted any jobs for the week. System will notify Pilot that no jobs has been accepted yet. Removed "1. The pilot check assigned jobs" and "2. The system displays weekly job assigned by manager" from Main Success Scenarios. Precondition include "pilot is already in the View Weekly Job Assignment page" to reduce complexity of sequence diagram. Postcondition updated to clearly explain the outcome.

> - [ ] Update number of transaction. -1

- UC-2:

> Change Precondition to state that Pilot should already be in the View Weekly Job Assignment page. Postcondition changed from NA to "All jobs assigned to the pilot for the week is displayed" as postcondition should not be empty.

- UC-3:

> Change Precondition to state that Pilot should already be in the Availability Page to limit complexity of sequence diagram. Removed "1. Pilot click on the availability page" and "2. System display availability page" from Main Success Scenarios. 

> - [ ] Update number of transaction. -1

- UC-4:

> Change Precondition to state that Pilot should already be in the Profile page. Removed "1. Pilot selects the profile page." and "2. System display profile page" from Main Success Scenarios.

> - [ ] Update number of transaction. -1

- UC-5:

> Change Precondition to state that Manager should already be in the flight schedule page. Removed "1. Manager clicks on the flight schedule page" and "2. System displays the flight schedule page" from Main Success Scenarios. Postconditions changed from NA to Manager will be able to see that all flights has been allocated to a pilot.

> - [ ] Update number of transaction. -1


- UC-6:

> Change Precondition to state that Manager should already be in the Job Allocation page. Removed "1. Manager clicks on the job allocation page." and "2. System displays the flight schedule to be allocated for the week" from Main Success Scenarios. Manager will now be assigning a pilot (instead of 2) to 1 job as no requirements stated that. Postconditions removed the word "main: " to align with other use case descriptions.

> - [ ] Update number of transaction. -1

> - [ ] @geethika-m note that Pilot 2 and Pilot 3 box has been deleted from the Job Allocation Page in figma and Pilot 1 is changed to Pilot chosen, feel free to edit it.

- UC-7:

> Change Precondition to state that Manager should already be in the Pilot Profile page. Removed "1. Manager selects the training page" and "2. System displays the all the pilot’s name and their current
training progress" from Main Success Scenarios. Postconditions updated from NA to "Rank of Pilot is updated.". 

> - [ ] Update number of transaction. -1

- UC-8:

> Change Precondition to state that Manager should already be on the landing page. Removed "1. Manager goes to the dashboard page to check pilots’ working hours." from Main Success Scenarios. Postconditions updated from NA to "Top 3 pilots with the least working hours and a list of over worked pilot displayed". 

> - [ ] @dennisawj I've highlighted that most of the success scenarios to get to the required page is removed, any suggestion? Please advice.

- UC-9:

> Change Precondition to state that IT Admin should already be in the add user page. Removed "1. IT Admin select the add user option." and "2. System display creates user form." from Main Success Scenarios. 

> - [ ] Update number of transaction. -1

- UC-10:

> Change Precondition to state that IT Admin should already be in the delete user page and that DB is connected. Removed "1. IT admin select view user option" and "2. System display the complete list of user
" from Main Success Scenarios. Postconditions updated from NA to "Remove user from DB. Close DB connection". 

> - [ ] Update number of transaction. -1

- UC-11: 

>  Change Precondition to state that pilot should already be in the View Weekly Job Assignment page. Removed "1. The pilot check assigned Job" and "2. The system displays weekly job assigned by manager
" from Main Success Scenarios. Postcondition updated to clearly explain the outcome.

> - [ ] Update number of transaction. -1

**Comment by dennisawj** [comment]
` I've highlighted that most of the success scenarios to get to the required page is removed, any suggestion? Please advice.`

Regarding UC-8, I feel it is needed to include that in the scenario to show that there is a transaction. It would be weirder without it since there would only be 1 step in the main success scenario. Another alternative is we change the description to remove the "is on landing page" part so that there won't be any duplicates.

**Comment by zoee-Y** [comment]
Completed on 29/10/22
