### ISSUE TITLE
2.4.3 Project Status & work allocation

### ISSUE THREAD

**Issue by minXnub** [minXnub/ICT2101-P4-3-Project#71]
To be completed by 10/28/22

Gantt Chart
https://docs.google.com/spreadsheets/d/1P6o2QLqJXjf93TGs4Vj24MOylW6LWjjHitjJYCuA2Kk/edit?

**Comment by minXnub** [comment]
Updated Gantt Chart

**Comment by zoee-Y** [comment]
Updated Gantt Chart (14/10/22):

- Updated start and due date for 2.3.1, 2.3.1 and 2.6

**Comment by geethika-m** [comment]
Updated Gantt Chart (14/10/22):

- Updated Percentile of task completion for Section 2.2 and 2.2.1 (Non-functional and safety requirements) to 50%

**Comment by minXnub** [comment]
Completed the Team Dynamics, Project Status, Overruns and Work allocation descriptions.

**Comment by minXnub** [comment]
Completed

**Comment by minXnub** [comment]
Updated Project Status to explain the tasks completed in week 9. We are on track for submission

**Comment by minXnub** [comment]
Closed on 29 Oct as completed
