### ISSUE TITLE
2.6 Appendix C  Overall Class Diagram

### ISSUE THREAD

**Issue by dennisawj** [minXnub/ICT2101-P4-3-Project#73]
Deadline: 28/10/22

To do:
(Related to 2.3.2 Detailed design)
- Come up with class diagram with team by 28/10/22

**Comment by minXnub** [comment]
Completed Class diagram together on 19 October 2022 and gathered feedback on the 21 Oct 2022.

**Comment by zoee-Y** [comment]
Completed on 29/10/22
