### ISSUE TITLE
2.2.1 Use Case Model

### ISSUE THREAD

**Issue by zoee-Y** [minXnub/ICT2101-P4-3-Project#75]

**Comment by geethika-m** [comment]
To do:

- Add extension point for use case model
- Check if existing use cases are correct and add in new use cases to match new requirements.

**Comment by minXnub** [comment]
Completed the explanation for the changes made to UC-1.

**Comment by geethika-m** [comment]
Completed

**Comment by geethika-m** [comment]
Closed as completed
