### ISSUE TITLE
2.2.3 Non-functional Requirements

### ISSUE THREAD

**Issue by zoee-Y** [minXnub/ICT2101-P4-3-Project#76]

**Comment by geethika-m** [comment]
To do:

- Technical research to come up with new non-functional requirements
- Ensure existing requirements from previous phase are correct

**Comment by minXnub** [comment]
Change NFR1 to include maintainbility in the software

**Comment by geethika-m** [comment]
Completed

**Comment by geethika-m** [comment]
Closed as completed
