### ISSUE TITLE
2.2.4 Requirement Validation

### ISSUE THREAD

**Issue by zoee-Y** [minXnub/ICT2101-P4-3-Project#78]

**Comment by geethika-m** [comment]
To do:

- Perform validation for requirements to ensure that all requirements are correct and viable.

**Comment by minXnub** [comment]
Confirmed that Test case generation should be in M3. Therefore, screenshot of meeting minutes was inserted.

**Comment by geethika-m** [comment]
Completed

**Comment by geethika-m** [comment]
Closed as completed
