### ISSUE TITLE
1.3.4.1 Performance Requirements

### ISSUE THREAD

**Issue by minXnub** [minXnub/ICT2101-P4-3-Project#8]

**Comment by minXnub** [comment]
Reviewed

**Comment by dennisawj** [comment]
Reviewed

**Comment by zoee-Y** [comment]
Reviewed

**Comment by geethika-m** [comment]
Wrote the performance requirements for our project, based on our discussions, the project brief, and the client meeting.

**Comment by geethika-m** [comment]
Closed as completed
