### ISSUE TITLE
Improvement for team (M2): task allocation

### ISSUE THREAD

**Issue by zoee-Y** [minXnub/ICT2101-P4-3-Project#80]

**Comment by minXnub** [comment]
Deadline = ?
1. Allocate task by everyone by xx Oct 2022.
2. Team management by Mickey Mouse by yy Oct 2022.

-----------------
Issue completed on zzz Nov 2022. We are late by 10 days./ We are on time.
Here is the final product

**Comment by dennisawj** [comment]
Task allocation for milestone 2:
  Task      :   In-Charge
   2.1      -     Dennis 
   2.2      -     Geethika
   2.3      -     Zoe
   2.4      -     Shumin

Team Management by Dennis

----------------

**Comment by dennisawj** [comment]
Completed on 29/10/22
