### ISSUE TITLE
2.4.2 Updated Overall Time Required

### ISSUE THREAD

**Issue by minXnub** [minXnub/ICT2101-P4-3-Project#81]
Deadline: 28 Oct 2022

**Comment by minXnub** [comment]
Completed

**Comment by zoee-Y** [comment]
Reviewed

**Comment by dennisawj** [comment]
Reviewed

**Comment by minXnub** [comment]
Closed as Completed on 27 Oct 2022

**Comment by minXnub** [comment]
Reopen issue to edit the number of transaction for each use case.

**Comment by minXnub** [comment]
Changes in number of transaction did not resulted in any changes to the Total Unadjusted Points (UUCW) calculation. Close as Completed on 29 Oct 2022
