### ISSUE TITLE
2.2.2 Functional Requirements

### ISSUE THREAD

**Issue by geethika-m** [minXnub/ICT2101-P4-3-Project#83]

**Comment by geethika-m** [comment]
Deadline: 29 Oct 2022

To do:
- Add in new functional requirements

**Comment by geethika-m** [comment]
Completed writing about the new functional requirement and new user interface requirement regarding the manual acceptance of job assignments on 28 Oct 2022.

**Comment by minXnub** [comment]
Removed FR1 to FR10 as no changes made to those functional requirements

**Comment by geethika-m** [comment]
Completed

**Comment by geethika-m** [comment]
Closed as completed
