### ISSUE TITLE
3.3 Black-box Testing

### ISSUE THREAD

**Issue by geethika-m** [minXnub/ICT2101-P4-3-Project#88]
Due: 26 Nov 2022

**Comment by dennisawj** [comment]
added test scenario for user management for IT Admin and isManager( ).  
Worked on the decision table with the team.

**Comment by zoee-Y** [comment]
Test scenario allocation:
Zhi wei:
- userValidation
- updateDatabase(User)

Dennis
- user management it admin
- isManager

Geethika:
- pilot availability checkUser+checkAction(action)
- job allocation updateDatabase

Shumin:
- availability updateDatabase

**Comment by zoee-Y** [comment]
Did test scenario for userValidation(email, password) and updateDatabase(User) methods.
Worked on decision tables with the team

**Comment by minXnub** [comment]
Completed test scenario for availability updateDatabase on 26 Nov 2022

**Comment by minXnub** [comment]
Closed as Completion on 26 Nov 2022
