### ISSUE TITLE
3.5 Project Prototype & Wireframes

### ISSUE THREAD

**Issue by geethika-m** [minXnub/ICT2101-P4-3-Project#90]
Due: 26 Nov 2022

**Comment by geethika-m** [comment]
To do:

1. Design and refine final prototypes on Figma 
2. Record and edit video demonstration for our prototype (to be done by Zoe, Dennis & Shu Min)
3. Update github readme.md with prototype links and steps on how to access and navigate

**Comment by geethika-m** [comment]
- Completed designing and refining all the prototype screens on 26/11/22 for IT Adminstrators, Managers and Pilots on Figma. 
- Added Prototype links on 26/11/22 on team's github readme.md file and added step by step instructions on how to access the prototype.

**Figma links:**
Manager: 
https://www.figma.com/proto/0g9uQStvRXzD6M5yn37VmX/Flight-Management-System-(ICT2101)?node-id=245%3A392&scaling=scale-down&page-id=0%3A1&starting-point-node-id=245%3A392 
 
Staff: 
https://www.figma.com/proto/0g9uQStvRXzD6M5yn37VmX/Flight-Management-System-(ICT2101)?node-id=245%3A334&scaling=scale-down&page-id=3%3A2&starting-point-node-id=245%3A334 
 
IT admin: 
https://www.figma.com/proto/0g9uQStvRXzD6M5yn37VmX/Flight-Management-System-(ICT2101)?node-id=55%3A103&scaling=scale-down&page-id=27%3A67&starting-point-node-id=55%3A103

**Comment by zoee-Y** [comment]
Recorded IT admin part of prototype for the video

**Comment by dennisawj** [comment]
Recorded Manager Part of prototype for video , edited the video and uploaded on youtube

**Comment by minXnub** [comment]
Recorded Pilot part of video prototype

**Comment by geethika-m** [comment]
Closed as completed
